name: 'Dispatch a new image message on a gitops repo'
description: >
  Using state repo structure it updates an image value and the creates 
  a pull request in the same state repo
inputs:
  application:
    description: 'Application to read from config.yaml'
    required: true
    default: ''
  environment:
    description: 'Environment to select from config.yaml'
    required: true
    default: ''
  services:
    description: 'Comma separeted list of services'
    required: true
    default: ''
  image:
    description: 'New image value'
    required: true
    default: ''
  reviewers:
    description: 'Reviewers of the new PR'
    required: false
    default: ''
  pr_title:
    description: 'The title of the PR'
    required: false
    default: ''
  pr_body:
    description: 'Body of the PR'
    required: false
    default: ''
  branch_name:
    description: 'Name of the new branch used to pull request'
    required: false
    default: ''
  token:
    description: >
      Personal access token (PAT) used to fetch the repository. The PAT is configured
      with the local git config, which enables your scripts to run authenticated git
      commands. The post-job step removes the PAT.
      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.
      [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    default: ${{ github.token }}

runs:
  using: 'node12'
  main: 'dist/index.js'
